### ISSUE TITLE
mutex locked issue seen during network interface disconnect

### ISSUE THREAD

**Issue by atan1** [cybergarage/uecho#1]
Hello,
We ran into an issue where upon loss of network interface connection (eth0 went down), our process got stuck waiting for uecho_mutex_lock() in uecho_controller_postmessage().  From code review, we believe the issue is due to a prior call to uecho_controller_postmessage() where it failed to send a message and returned prior to unlocking the mutex.  We made the fix below and it has resolved our issue.  Now, when the network interface is lost, the process no longer hangs and is able to resume operation once the network interface has been restored.

In controller.c, we add the code in bold below.

/****************************************
 * uecho_controller_postmessage
 ****************************************/

bool uecho_controller_postmessage(uEchoController *ctrl, uEchoObject *obj, uEchoMessage *reqMsg, uEchoMessage *resMsg)
{
  bool isResponceReceived;
  int n;

  if (!ctrl)
    return false;

  uecho_mutex_lock(ctrl->mutex);

  uecho_controller_setpostrequestmessage(ctrl, reqMsg);
  uecho_controller_setpostresponsemessage(ctrl, resMsg);

  if (!uecho_controller_sendmessage(ctrl, obj, reqMsg)) **{
    uecho_mutex_unlock(ctrl->mutex);**
    return false;
  **}**

  isResponceReceived = false;
  for (n=0; n<uEchoControllerPostResponseLoopCount; n++) {
    uecho_sleep(ctrl->postResWaitMiliTime / uEchoControllerPostResponseLoopCount);
    if (uecho_controller_ispostresponsereceived(ctrl)) {
      isResponceReceived = true;
      break;
    }
  }

  uecho_controller_setpostrequestmessage(ctrl, NULL);
  uecho_controller_setpostresponsemessage(ctrl, NULL);

  uecho_mutex_unlock(ctrl->mutex);

  return isResponceReceived;
}

**Comment by cybergarage** [comment]
@atan1 c
I fixed the problem and release it as v0.9.2 now.
Thanks for your report.

**Comment by atan1** [comment]
Thanks Konno-san.  Also, thank you for developing and sharing your uecho
package.
